### ISSUE TITLE
Upscaling to 1080?

### ISSUE THREAD

**Issue by TS000** [ex-zee-ex/spectral_mesh#1]
First off, I'm a huge fan of this project: Open source ✅ , DIY aesthetic ✅ , the creator is into less digital waste ✅ . Now, I'm looking to contribute and want to figure out a way to add an upscale of the 720p output to 1080p on the software side. I'm new to visualization software and I'm wondering if upscaling is a feature that was already tried out and found to be blocked by either hardware or something else?

Thanks!

**Comment by ex-zee-ex** [comment]
howdy!  upscaling to 720 or 1080 onboard is gonna drop yr framerates down
to very noticably low rates, this unit can only do 480p right now.  pretty
much just a overall hardware limitation, just not enough processing power
for high numbers of pixels!  I'm not 100 percent positive that it would be
impossible to implement a version of this project with higher resolutions
but i think it would likely need to be completely rebuilt from the bottom
up and that there would be a good chance that any way it gets rewritten it
goes the fps would max out in the 10-20 range for 720 and 8-12 for 1080.

**Comment by TS000** [comment]
Ah! I had a feeling the mighty RP would maybe bottle neck. Thanks for the quick response!
